---
#Перезапуск сервера
- name: "Reboot"
  ansible.builtin.reboot:

#Reload службы fail2ban
- name: "Reload fail2ban"
  ansible.builtin.systemd_service:
    name: "fail2ban"
    state: "reloaded"
    enabled: true