---
- name: "Restart keepalived"
  ansible.builtin.systemd_service:
    name: "keepalived"
    state: "restarted"
  when: "status_keepalived.rc == 0"

- name: "Reload angie"
  ansible.builtin.systemd_service:
    name: "angie"
    state: "reloaded"
  when: "status_angie.rc == 0"