---
- name: "Restart php-fpm"
  ansible.builtin.systemd_service:
    name: "php-fpm"
    state: "restarted"
  when: "status_phpfpm.rc == 0"

- name: "Reload angie"
  ansible.builtin.systemd_service:
    name: "angie"
    state: "reloaded"
  when: "status_angie.rc == 0"